export const GET_MESSAGES = "GET_MESSAGES";
export const GET_USER_MESSAGES = "GET_USER_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

export const MESSAGE_ERROR = "MESSAGE_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const POST_PROFILE_FAIL = "PROFILE_FAIL";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
